# Generated by Django 2.1.7 on 2019-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artical_name', models.CharField(max_length=100)),
                ('Artical_author', models.CharField(max_length=50)),
                ('Artical_image_name', models.CharField(max_length=30)),
                ('Artical_image', models.ImageField(upload_to='images/')),
                ('Artical_here', models.CharField(max_length=1500)),
            ],
        ),
    ]
